### ISSUE TITLE
dns改不成功

### ISSUE THREAD

**Issue by wdkwdkwdk** [lioonline/OS-X-El-Capitan#3]
在host里面改好了DNS，ping也ping到本地ip地址了，但是浏览器访问的话还是远程的，求解

**Comment by nsleejian** [comment]
那应该是你的目录路径设置不对

**Comment by wdkwdkwdk** [comment]
@lioonline 不是啊，我直接访问localhost都行的～

**Comment by wdkwdkwdk** [comment]
@lioonline  找到原因了～开了ss加速忘关了。。。
